on:
  push:
    branches:
      - master
      - dev
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  UKWA-UI_build_and_push_to_registry_job:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=min2ha/ukwa-ui:latest
          cache-to: type=inline
          tags: min2ha/ukwa-ui:latest
#          build-args: PROFILE=dev,ARG2=test
